#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 10 14:05:54 2021

@author: nils
"""

from typing import List

class ProbabilityTable:
    
    
    def __init__(self, variables: List[str]):
        self.variables = variables
        